// This file is generated by `scripts/categorize-requests.ts`
export {
	getFederatedActivity,
	type GetFederatedActivityParams,
	type GetFederatedActivityResult,
	getFederatedActivitiesByAccount,
	type GetFederatedActivitiesByAccountParams,
	type GetFederatedActivitiesByAccountResult,
	getFederatedActivitiesByAccounts,
	type GetFederatedActivitiesByAccountsParams,
	type GetFederatedActivitiesByAccountsResult,
	getFederatedNetworkActivities,
	type GetFederatedNetworkActivitiesParams,
	type GetFederatedNetworkActivitiesResult,
	getFederatedPlatformActivities,
	type GetFederatedPlatformActivitiesParams,
	type GetFederatedPlatformActivitiesResult,
} from "./requests";
